version: "3.8"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
